apiVersion: projectcalico.org/v3
kind: BFDConfiguration
metadata:
  name: bgp-default
  namespace: desire6g
spec:
  nodeSelector: "all()"
  interfaces:
    - matchPattern: "*"
      minimumRecvInterval: 10ms
      minimumSendInterval: 100ms
      idleSendInterval: 1m
      multiplier: 5

---

apiVersion: projectcalico.org/v3
kind: BGPPeer
metadata:
  name: my-global-peer
  namespace: desire6g
spec:
  peerIP: 192.168.49.2
  asNumber: 64567
