apiVersion: v1
kind: Namespace
metadata:
  name: tigera-operator
---
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
  namespace: cluster
spec:
  calicoNetwork:
    bgp: Disabled
    ipPools:
      - cidr: 198.51.100.0/24
        encapsulation: VXLAN
