{{- if .Values.configmap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "agent.fullname" . }}-config
  labels:
{{ include "agent.labels" . | nindent 4 }}
  {{- with .Values.configmap.annotations }}
  annotations:
{{ toYaml . | nindent 4 }}
  {{- end }}
data:
  config.json: |-
{{ .Files.Get "config.json" | indent 4 }}
{{- end }}
