apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-config
  namespace: desire6g
  labels:
    app: agent
data:
  config-agent.json: |
    {
      "role": "agent",
      "host": "0.0.0.0",
      "port": 80,
      "target_url": "http://mlfo.desire6g.local:80/process",
      "latency_threshold": 1,
      "message": {"status": "QoS violated, need reconfiguration"}
    }
